### ISSUE TITLE
USBデバッグモード無し動作

### ISSUE THREAD

**Issue by Zaakko** [amate/scrsndcpy#2]
USBデバッグモード無しで動作するように拡張可能でしょうか。

Adroid側のアプリがUSBデバッグモードが有効だと動作しない場合があるので、機能追加して頂けると助かります。

ちなみに使用方法はPC側に画面出力するだけなのでAndroid側を操作できる必要は無いです。（画面ミラーリング利用のみ）

例えばPC側に画面出力が開始されたらUSBデバッグモードをOFFにしても画面出力が継続出来る、といった拡張でも問題ないです。

**Comment by amate** [comment]
仕様上デバッグモードは必須です
すみません
