### ISSUE TITLE
Support for combining the scrcpy and sndcpy output into one window

### ISSUE THREAD

**Issue by TragicLifeHu** [amate/scrsndcpy#3]
There's applications like Discord, if I try to broadcast the Android window, as sndcpy is running in other process, sound won't be captured.
Discordのようなアプリがありますが、Androidのウィンドウをブロードキャストしようとすると、sndcpyが別のプロセスで動いているため、音声がキャプチャされません。

I think creating a window frame, and run both commends inside, may solve the problem.
ウィンドウフレームを作成し、内部で両方のコマンドを実行すると、問題が解決する可能性があると思います。

I tested the original sndcpy batch, the sound of window created by that commend can be streamed to Discord.
オリジナルのsndcpyバッチをテストしたところ、その方法で作成されたウィンドウのサウンドはDiscordにストリーミングできました。

**Comment by amate** [comment]
v1.4で対応しました
