### ISSUE TITLE
音声ストリーミング再生が失敗する

### ISSUE THREAD

**Issue by JAM924** [amate/scrsndcpy#4]
Screen Sound Copyボタンを押した際、スマホ画面の再生と操作はできるのですが、Socket Error - audio streaming finishというログが出て音声の再生ができず、リトライが一定回数行われた後スマホ画面も消えます。
以下がinfoログです。
[info.log](https://github.com/amate/scrsndcpy/files/10777132/info.log)

[使用環境]
端末: Sony Xperia 5 II (A002SO)
Androidバージョン: 11
ビルド番号: 58.1.D.6.129
接続方法: USBとwifi(どちらも上記症状が発生)

**Comment by amate** [comment]
https://github.com/amate/scrsndcpy/releases
古いバージョンではどうですかね？
1.3か1.2でも同じように音声が出ませんか？

**Comment by JAM924** [comment]
1.3だと音声再生できました！
